# Generated by Django 5.1.4 on 2024-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_booking_options_specialist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Персональный код мастера'),
        ),
    ]
