# Generated by Django 5.1.4 on 2024-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_specialist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код процедуры'),
        ),
    ]
