# Generated by Django 5.1.4 on 2024-12-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_procedure_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=15)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bot.procedure')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bot.salon')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bot.specialist')),
            ],
            options={
                'unique_together': {('specialist', 'date', 'time')},
            },
        ),
    ]
