# Generated by Django 5.1.4 on 2024-12-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_appointment_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bot.salon'),
        ),
    ]
