# Generated by Django 5.1.4 on 2024-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_appointment_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
    ]
