# Generated by Django 5.1.4 on 2024-12-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код салона'),
        ),
    ]
