# Generated by Django 5.1.4 on 2024-12-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_salon_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('procedure', 'client')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
